bebop101/charge_station/x: 0.55
bebop101/charge_station/y: 0.7
bebop101/charge_station/r: 0.3
bebop101/initialEnergy: 4000
bebop102/charge_station/x: -0.55
bebop102/charge_station/y: 0.7
bebop102/charge_station/r: 0.3
bebop102/initialEnergy: 3300
bebop103/charge_station/x: 0.0
bebop103/charge_station/y: -0.3
bebop103/charge_station/r: 0.3
bebop103/initialEnergy: 2600
