field:
  mech_acc: [200,200,100] #x,y,theta
  limit: [[-2,2], [-2,2],[-0.785398163, 0.785398163]] #[x[min,max], y[min,max], theta[min,max]]
bebop101:
  initial_pose:
    x: -1
    y: 0
    z: 1
bebop102:
  initial_pose:
    x: 1
    y: 0
    z: 1