bebop101:
  initial_pose:
    x: 1.0
    y: 0
    z: 1
bebop102:
  initial_pose:
    x: -1.0
    y: 0
    z: 1
field:
  dim: 2
  mesh_acc: [200,100] #x,theta
  limit: [[-1.3, 1.3],[-0.8,0.8]] #[x[min,max], theta[min,max]]
sigma: 0.1