bebop101:
  initial_pose:
    x: 1.0
    y: 0
    z: 1
bebop102:
  initial_pose:
    x: -1.0
    y: 0
    z: 1
field:
  dim: 2
  mesh_acc: [200,100] #x,theta
  limit: [[0, 1.0],[0,0.69813]] #[x[min,max], theta[min,max]]
sigma: 0.1
clock:
  central: 20
  posecollector: 100
  agent: 2