clock: 20
bebop101:
  initial_pose:
    x: 1.0
    y: 0.0
    z: 1
bebop102:
  initial_pose:
    x: -1.0
    y: -0.0
    z: 1
bebop103:
  initial_pose:
    x: 0.0
    y: 0.6
    z: 1
bebop104:
  initial_pose:
    x: -0.0
    y: -0.5
    z: 1
observe_field:
  # mesh_acc: [100,100,5, 10,10] #x,y,z, yaw, pitch
  mesh_acc: [100,100,5, 5, 60] #x,y,z, yaw, pitch
  limit: [[-1.0, 1.0],[-1.0,1.0],[0.0,0.5],[0.78, 1.5707963], [-3.14159265358979,3.14159265358979]] #[x[min,max], theta[min,max], z[min,max]] 
drone_field:
  mesh_acc: [101, 101] #x (should contain 0 in linspace for compress)
  limit: [[-1.5, 1.5], [-1.5, 1.5]] #[x[min,max]] 
rviz_field:
  mesh_acc: [101, 101] #x (should contain 0 in linspace for compress)
  limit: [[-1.5, 1.5], [-1.5, 1.5]] #[x[min,max]] 

theta_field:
  mesh_acc: [100, 100] #x (should contain 0 in linspace for compress)
  limit: [[1.0471975511966, 1.5707963], [-3.14,3.14]] #[x[min,max]] 
  # theta_target:
  #   - target:
  #       x: 0
  #       y: 0
  #     show:
  #       x: -0.5
  #       y: 3
  #   - target:
  #       x: -1.0
  #       y: 1.0
  #     show:
  #       x: -1.5
  #       y: 3
  
sigma: 0.1
clock:
  central: 20
  posecollector: 20
  agent: 20